version: '3.8'

# comment
services:
  dbt:
    image: python:3.9-slim
    container_name: dbt_dev
    working_dir: /app
    volumes:
      - .:/app
    entrypoint: ["sh", "/app/entrypoint.sh"]
    environment:
      - DBT_PROFILES_DIR=/app/profiles
    ports:
      - "8080:8080"

