curves_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: host.docker.internal
      user: myuser
      password: mypassword
      port: 5432
      dbname: mydatabase
      schema: dev

    prod:
      type: postgres
      host: host.docker.internal
      user: myuser
      password: mypassword
      port: 5432
      dbname: mydatabase
      schema: prod
